version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-backend:latest
    container_name: spring_backend
    ports:
      - "8081:8080"   # change to avoid port conflict
    environment:
      - MONGO_URI
      - FRONTEND_URL
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
